PROFILES = {
    "c0_only": [],
    "c0_bg4": ["log", "ping", "sysmon", "output"],
    "c0_bg4_heavy": ["log", "ping", "sysmon", "output_heavy"],
}

DEFAULT_TARGETS = "vim,nano"
DEFAULT_PROBE_TEXT_FILE = "payloads/probe_text.c"

SAMPLE_FIELDS = [
    "run_id",
    "block_id",
    "trial_order",
    "trial_id",
    "ts",
    "protocol",
    "measurement_mode",
    "target",
    "profile",
    "sample_idx",
    "char_index",
    "char_total",
    "source_offset",
    "source_char_total",
    "source_line",
    "source_column",
    "token",
    "status",
    "latency_ms",
    "stall",
    "background_channels",
    "channel_count",
    "channel_open_failures",
    "note",
]

TRIAL_FIELDS = [
    "run_id",
    "block_id",
    "trial_order",
    "trial_id",
    "protocol",
    "measurement_mode",
    "target",
    "profile",
    "expected_chars",
    "completed_chars",
    "completion_rate_pct",
    "incomplete_count",
    "incomplete_rate_pct",
    "median_ms",
    "p95_ms",
    "p95_publishable",
    "effective_mean_ms",
    "effective_p95_ms",
    "timeout_count",
    "status_counts",
    "stall_count",
    "connection_valid",
    "channel_ready",
    "started_ts",
    "ended_ts",
    "note",
]

CHANNEL_COUNTER_FIELDS = [
    "run_id",
    "block_id",
    "trial_order",
    "trial_id",
    "protocol",
    "target",
    "profile",
    "role",
    "stream_id",
    "bytes_received",
    "duration_s",
    "average_bytes_per_s",
    "ready",
    "note",
]
